version: '3.6'
services:
  chartify:
    build:
      context: ./
      args:
        ALPINE_SERVER: ${ALPINE_SERVER}
    volumes:
      - .:/app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: chartify

  nginx:
    build: ./nginx/
    ports:
      - ${NGINX_PORT:-8080}:80
    environment:
      NGINX_PORT: ${NGINX_PORT:-8080}
    depends_on:
      - chartify

  mysql:
    image: mysql:5
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chartify

