version: '3.6'

services:
  chartify:
    build: ./
    volumes:
      - .:/app
    ports:
      - 9292:9292
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD:
      DB_DBNAME: chartify

  nginx:
    build: ./nginx/
    ports:
      - 8080:80
    depends_on:
      - chartify

  postgres:
    image: postgres:10-alpine

