version: '3.6'
services:
  chartify:
    build:
      context: ./
      args:
        ALPINE_SERVER: ${ALPINE_SERVER}
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD:
      DB_DBNAME: chartify

  nginx:
    build: ./nginx/
    ports:
      - ${NGINX_PORT:-8080}:80
    environment:
      NGINX_PORT: ${NGINX_PORT:-8080}
    depends_on:
      - chartify

  postgres:
    image: postgres:10-alpine

